package com.rewritesolutions.ai.spring_ai_app.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * JPA Entity representing a customer in the system.
 * This entity maps to the "customers" table in the database.
 *
 * <p>The Customer entity includes automatic timestamp management through JPA lifecycle callbacks
 * ({@link PrePersist} and {@link PreUpdate}) to track creation and modification times.</p>
 *
 * <p>Uses Lombok annotations to reduce boilerplate code:
 * <ul>
 *   <li>{@link Data} - generates getters, setters, toString, equals, and hashCode</li>
 *   <li>{@link Builder} - provides builder pattern for object construction</li>
 *   <li>{@link NoArgsConstructor} - generates no-args constructor (required by JPA)</li>
 *   <li>{@link AllArgsConstructor} - generates all-args constructor (required by Builder)</li>
 * </ul>
 *
 * @author Rewrite Solutions
 * @version 1.0
 * @since 1.0
 */
@Entity
@Table(name = "customers")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Customer {

    /** Unique identifier for the customer, auto-generated by database */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Customer's first name (required field) */
    @Column(nullable = false)
    private String firstName;

    /** Customer's last name (required field) */
    @Column(nullable = false)
    private String lastName;

    /** Customer's email address, must be unique across all customers (required field) */
    @Column(unique = true, nullable = false)
    private String email;

    /** Customer's phone number (optional field) */
    @Column(name = "phone_number")
    private String phoneNumber;

    /** Timestamp when the customer record was created (auto-managed, immutable) */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp when the customer record was last updated (auto-managed) */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * JPA lifecycle callback invoked before the entity is persisted to the database.
     * Automatically sets the {@link #createdAt} and {@link #updatedAt} timestamps.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    /**
     * JPA lifecycle callback invoked before the entity is updated in the database.
     * Automatically updates the {@link #updatedAt} timestamp.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}